/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< LPUART1 signal: RX */

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< LPUART1 signal: TX */

/* GPIO_B0_11 (coord A10), LCDIF_D7/BT_CFG[7] */
#define BOARD_INITPINS_LCDIF_D7_GPIO                                       GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D7_PORT                                       GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D7_PIN                                          11U   /*!< GPIO2 pin index: 11 */

/* GPIO_B0_00 (coord D7), LCDIF_CLK */
#define BOARD_INITPINS_LCDIF_CLK_GPIO                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_CLK_PORT                                      GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_CLK_PIN                                          0U   /*!< GPIO2 pin index: 0 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_B0_03 (coord D8), LCDIF_VSYNC */
#define LPSPI4_INITPINS_LCDIF_VSYNC_PERIPHERAL                            LPSPI4   /*!< Device name: LPSPI4 */
#define LPSPI4_INITPINS_LCDIF_VSYNC_SIGNAL                                   SCK   /*!< LPSPI4 signal: SCK */

/* GPIO_B0_02 (coord E8), LCDIF_HSYNC */
#define LPSPI4_INITPINS_LCDIF_HSYNC_PERIPHERAL                            LPSPI4   /*!< Device name: LPSPI4 */
#define LPSPI4_INITPINS_LCDIF_HSYNC_SIGNAL                                   SDO   /*!< LPSPI4 signal: SDO */

/* GPIO_B0_01 (coord E7), LCDIF_ENABLE */
#define LPSPI4_INITPINS_LCDIF_ENABLE_PERIPHERAL                           LPSPI4   /*!< Device name: LPSPI4 */
#define LPSPI4_INITPINS_LCDIF_ENABLE_SIGNAL                                  SDI   /*!< LPSPI4 signal: SDI */

/* GPIO_B1_04 (coord E12), ENET_RXD0 */
#define LPSPI4_INITPINS_ENET_RXD0_PERIPHERAL                              LPSPI4   /*!< Device name: LPSPI4 */
#define LPSPI4_INITPINS_ENET_RXD0_SIGNAL                                    PCS0   /*!< LPSPI4 signal: PCS0 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI4_InitPins(void);

/* GPIO_SD_B0_00 (coord J4), SD1_CMD/J24[6] */
#define LPSPI4_DEINITPINS_SD1_CMD_GPIO                                     GPIO3   /*!< GPIO device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_CMD_PORT                                     GPIO3   /*!< PORT device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_CMD_PIN                                        12U   /*!< GPIO3 pin index: 12 */

/* GPIO_SD_B0_01 (coord J3), SD1_CLK/J24[3] */
#define LPSPI4_DEINITPINS_SD1_CLK_GPIO                                     GPIO3   /*!< GPIO device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_CLK_PORT                                     GPIO3   /*!< PORT device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_CLK_PIN                                        13U   /*!< GPIO3 pin index: 13 */

/* GPIO_SD_B0_02 (coord J1), SD1_D0/J24[4]/SPI_MOSI/PWM */
#define LPSPI4_DEINITPINS_SD1_D0_GPIO                                      GPIO3   /*!< GPIO device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_D0_PORT                                      GPIO3   /*!< PORT device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_D0_PIN                                         14U   /*!< GPIO3 pin index: 14 */

/* GPIO_SD_B0_03 (coord K1), SD1_D1/J24[5]/SPI_MISO */
#define LPSPI4_DEINITPINS_SD1_D1_GPIO                                      GPIO3   /*!< GPIO device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_D1_PORT                                      GPIO3   /*!< PORT device name: GPIO3 */
#define LPSPI4_DEINITPINS_SD1_D1_PIN                                         15U   /*!< GPIO3 pin index: 15 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI4_DeinitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
